applications/producto/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import ProductoView

url_principal = 'producto/'

urlpatterns = [
    path('', ProductoView.Inicio.as_view(), name='inicio'),
    path('nosotros/', ProductoView.Nosotros.as_view(), name='nosotros'),
    path('producto/', ProductoView.ProductoListaView.as_view(), name='producto'),
]

web/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include(('applications.producto.urls', 'productos'))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/common/models.py
from django.db import models

class Cat001Estado(models.Model):
    nombre = models.CharField(max_length=255, blank=True, null=True)
    codigo = models.CharField(max_length=3, blank=True, null=True)

    def __str__(self):
        return  self.nombre + ' ' + str(self.id)

    class Meta:
        managed = False
        db_table = 'cat_001_estado'
        ordering = ['id']

    verbose_name = 'ESTADO'
    verbose_name_plural = 'ESTADOS'

class Cat007TipoImagen(models.Model):
    estado_001 = models.ForeignKey(Cat001Estado, models.DO_NOTHING)
    nombre = models.CharField(max_length=255, blank=True, null=True)
    cod = models.CharField(max_length=3, blank=True, null=True)

    def __str__(self):
        return  self.nombre + ' ' + str(self.id)
    
    class Meta:
        managed = False
        db_table = 'cat_007_tipo_imagen'
        ordering = ['id']

    verbose_name = 'TIPO IMAGEN'
    verbose_name_plural = 'TIPOS DE IMAGENES'

applications/producto/models.py
from django.db import models
from applications.common.models import Cat001Estado, Cat007TipoImagen

# Create your models here.
class Pro041Tipo(models.Model):
    estado_001 = models.ForeignKey(Cat001Estado, models.DO_NOTHING)
    nombre = models.CharField(unique=True, max_length=255)
    codigo = models.CharField(unique=True, max_length=3)

    def __str__(self):
        return  self.nombre + ' ' + str(self.id)
    
    class Meta:
        managed = False
        db_table = 'pro_041_tipo'


class Pro042Producto(models.Model):
    estado_001 = models.ForeignKey(Cat001Estado, models.DO_NOTHING)
    tipo_041 = models.ForeignKey(Pro041Tipo, models.DO_NOTHING)
    nombre = models.CharField(unique=True, max_length=255, blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)
    dimesion = models.CharField(max_length=255, blank=True, null=True)
    marca_045 = models.ForeignKey('Pro045Marca', models.DO_NOTHING)
    peso = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return  self.nombre
    
    class Meta:
        managed = False
        db_table = 'pro_042_producto'


class Pro043ProductoValor(models.Model):
    estado_001 = models.ForeignKey(Cat001Estado, models.DO_NOTHING)
    fecha_creacion = models.DateField()
    fecha_actualizacion = models.DateField(blank=True, null=True)
    producto_042 = models.ForeignKey(Pro042Producto, models.DO_NOTHING)
    valor = models.IntegerField()
    cantidad = models.IntegerField(blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'pro_043_producto_valor'


class Pro044Imagen(models.Model):
    estado_001 = models.ForeignKey(Cat001Estado, models.DO_NOTHING)
    producto_042 = models.ForeignKey(Pro042Producto, models.DO_NOTHING)
    imagen_083_id = models.IntegerField()
    nombre_archivo = models.ImageField(upload_to='producto', blank=True, null=True)  # Nuevo campo de imagen
    tipo_007 = models.ForeignKey(Cat007TipoImagen, models.DO_NOTHING)

    def __str__(self):
        return  self.nombre
    
    class Meta:
        managed = False
        db_table = 'pro_044_imagen'


class Pro045Marca(models.Model):
    estado_001 = models.ForeignKey(Cat001Estado, models.DO_NOTHING)
    nombre = models.CharField(max_length=255, blank=True, null=True)
    logo = models.ImageField(upload_to='marca', blank=True, null=True)  # Nuevo campo de imagen

    class Meta:
        managed = False
        db_table = 'pro_045_marca'

applications/producto/views/ProductoView.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from ..models import Pro042Producto, Pro045Marca, Pro041Tipo, Pro044Imagen

# Create your views here.
class Inicio(TemplateView):
    """ vista que carga la pagina de inicio """
    template_name = 'base/index.html'

# Create your views here.
class Nosotros(TemplateView):
    """ vista que carga la pagina de inicio """
    template_name = 'base/nosotros.html'

class ProductoListaView(ListView):
    model = Pro042Producto
    template_name = 'producto/index.html'
    context_object_name = 'productos'
    paginate_by = 10  # Número de productos por página

    def get_queryset(self):
        queryset = super().get_queryset()

        # Filtrar por búsqueda (nombre o descripción)
        search_query = self.request.GET.get('q')
        if search_query:
            queryset = queryset.filter(
                Q(nombre__icontains=search_query) |
                Q(descripcion__icontains=search_query)
            )

        # Filtrar por marca
        marca_id = self.request.GET.get('marca')
        if marca_id:
            queryset = queryset.filter(marca_045_id=marca_id)

        # Filtrar por tipo
        tipo_id = self.request.GET.get('tipo')
        if tipo_id:
            queryset = queryset.filter(tipo_041_id=tipo_id)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['marcas'] = Pro045Marca.objects.all()
        context['tipos'] = Pro041Tipo.objects.all()
        return context

applications/producto/views/views.py
from django.shortcuts import render

# Create your views here.

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <!-- link stylesheet -->
    <link rel="stylesheet" href="{% static 'css/icofont.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/video-modal.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="relative font-inter font-normal text-base leading-[1.8] bg-bodyBg dark:bg-bodyBg-dark z-0">
    <!-- preloader -->
    <div
        class="preloader flex fixed top-0 left-0 h-screen w-full items-center justify-center z-xxl bg-whiteColor opacity-100 visible transition-all duration-700">
        <!-- spinner -->
        <div
            class="w-90px h-90px border-5px border-t-blue border-r-blue border-b-blue-light border-l-blue-light rounded-full animate-spin-infinit">
        </div>
        <div class="absolute top-1/2 left-1/2 -translate-y-1/2 -translate-x-1/2">
            <img src="{% static 'images/pre.png' %}" alt="Preloader" class="h-10 w-10 block">
        </div>
    </div>
    <!-- theme fixed shadow -->
    <div>
        <div class="fixed-shadow left-[-250px]"></div>
        <div class="fixed-shadow right-[-250px]"></div>
    </div>

    <!-- theme controller -->
    <div class="fixed top-[100px] 2xl:top-[300px] transition-all duration-300 right-[-50px] hover:right-0 z-xl">
        <button
            class="theme-controller w-90px h-10 bg-primaryColor dark:bg-whiteColor-dark rounded-l-lg2 text-whiteColor px-10px flex items-center dark:shadow-theme-controller">
            <!-- dark -->
            <svg xmlns="http://www.w3.org/2000/svg" class="mr-10px w-5 block dark:hidden" viewBox="0 0 512 512">
                <path
                    d="M160 136c0-30.62 4.51-61.61 16-88C99.57 81.27 48 159.32 48 248c0 119.29 96.71 216 216 216 88.68 0 166.73-51.57 200-128-26.39 11.49-57.38 16-88 16-119.29 0-216-96.71-216-216z"
                    fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32">
                </path>
            </svg>
            <span class="text-base block dark:hidden">Dark</span>
            <!-- light -->
            <svg xmlns="http://www.w3.org/2000/svg" class="hidden mr-10px w-5 dark:block" viewBox="0 0 512 512">
                <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="32"
                    d="M256 48v48M256 416v48M403.08 108.92l-33.94 33.94M142.86 369.14l-33.94 33.94M464 256h-48M96 256H48M403.08 403.08l-33.94-33.94M142.86 142.86l-33.94-33.94">
                </path>
                <circle cx="256" cy="256" r="80" fill="none" stroke="currentColor" stroke-linecap="round"
                    stroke-miterlimit="10" stroke-width="32"></circle>
            </svg>
            <span class="text-base hidden dark:block">Light</span>
        </button>
    </div>
    <!-- scroll up button -->
    <div>
        <button
            class="scroll-up w-50px h-50px leading-50px text-center text-primaryColor bg-white hover:text-whiteColor hover:bg-primaryColor rounded-full fixed right-5 bottom-[60px] shadow-scroll-up z-medium text-xl dark:text-whiteColor dark:bg-primaryColor dark:hover:text-whiteColor-dark hidden">
            <i class="icofont-rounded-up"></i>
        </button>
    </div>
    
    
    {% include 'base/cabecera.html' %}

    <!-- main body -->
    <main class="bg-transparent">

        {% block content %} {% endblock content %}
        
        
    </main>
    
    {% include 'base/PiePagina.html' %}

    <script src="{% static 'js/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/accordion.js' %}"></script>
    <script src="{% static 'js/chart.js' %}"></script>
    <script src="{% static 'js/count.js' %}"></script>
    <script src="{% static 'js/countdown.js' %}"></script>
    <script src="{% static 'js/counterup.js' %}"></script>
    <script src="{% static 'js/dropdown.js' %}"></script>
    <script src="{% static 'js/filter.js' %}"></script>
    <script src="{% static 'js/mobileMenu.js' %}"></script>
    <script src="{% static 'js/modal.js' %}"></script>
    <script src="{% static 'js/popup.js' %}"></script>
    <script src="{% static 'js/preloader.js' %}"></script>
    <script src="{% static 'js/scrollUp.js' %}"></script>
    <script src="{% static 'js/slider.js' %}"></script>
    <script src="{% static 'js/smoothScroll.js' %}"></script>
    <script src="{% static 'js/stickyHeader.js' %}"></script>
    <script src="{% static 'js/tabs.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script>
    <script src="{% static 'js/videoModal.js' %}"></script>
    <script src="{% static 'js/vanilla-tilt.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/base/cabecera.html
{% load static %}

<header>
    <!-- header top start -->
    <div class="bg-blackColor2 dark:bg-lightGrey10-dark hidden lg:block">
        <div
            class="container 3xl:container-secondary-lg 4xl:container mx-auto text-whiteColor text-size-12 xl:text-sm py-5px xl:py-9px">
            <div class="flex justify-between items-center">
                <div>
                    <p>WhatsApp: +57 3057115233 - Correo: info@devfer.com.co</p>
                </div>
                <div class="flex gap-37px items-center">
                    <div>
                        <p>
                            <i class="icofont-location-pin text-primaryColor text-size-15 mr-5px"></i>
                            <span>Bogot, Colombia</span>
                        </p>
                    </div>
                    <div>
                        <!-- header social list -->
                        <ul class="flex gap-13px text-size-15">
                            <li>
                                <a class="hover:text-primaryColor" href="#"><i class="icofont-facebook"></i></a>
                            </li>
                            <li>
                                <a class="hover:text-primaryColor" href="#"><i class="icofont-instagram"></i></a>
                            </li>
                            <li>
                                <a class="hover:text-primaryColor" href="#"><i class="icofont-youtube-play"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- header top end -->

    <!-- navbar start -->
    <div class="transition-all duration-500 sticky-header z-medium dark:bg-whiteColor-dark">
        <nav>
            <div
                class="py-15px lg:py-0 px-15px lg:container 3xl:container-secondary-lg 4xl:container mx-auto relative">
                <div class="grid grid-cols-2 lg:grid-cols-12 items-center gap-15px">
                    <!-- navbar left -->
                    <div class="lg:col-start-1 lg:col-span-2">
                        <a href="{% url 'productos:inicio' %}" class="block"><img src="{% static 'images/logo/logo_1.png' %}" alt="Logo"
                                class="w-logo-sm lg:w-auto py-2"></a>
                    </div>
                    <!-- Main menu -->
                    <div class="hidden lg:block lg:col-start-3 lg:col-span-7">
                        <ul class="nav-list flex justify-center">
                            <li class="nav-item group relative">
                                <a href="{% url 'productos:inicio' %}"
                                    class="px-5 lg:px-10px 2xl:px-15px 3xl:px-5 py-10 lg:py-5 2xl:py-30px 3xl:py-10 leading-sm 2xl:leading-lg text-base lg:text-sm 2xl:text-base font-semibold block group-hover:text-primaryColor dark:text-whiteColor">
                                    INICIO
                                </a>
                            </li>
                            <li class="nav-item group relative">
                                <a href="{% url 'productos:nosotros' %}"
                                    class="px-5 lg:px-10px 2xl:px-15px 3xl:px-5 py-10 lg:py-5 2xl:py-30px 3xl:py-10 leading-sm 2xl:leading-lg text-base lg:text-sm 2xl:text-base font-semibold block group-hover:text-primaryColor dark:text-whiteColor">
                                    NOSOTROS
                                </a>
                            </li>
                            <li class="nav-item group relative">
                                <a href="{% url 'productos:producto' %}"
                                    class="px-5 lg:px-10px 2xl:px-15px 3xl:px-5 py-10 lg:py-5 2xl:py-30px 3xl:py-10 leading-sm 2xl:leading-lg text-base lg:text-sm 2xl:text-base font-semibold block group-hover:text-primaryColor dark:text-whiteColor">
                                    PRODUCTOS
                                    <i class="icofont-rounded-down"></i>
                                </a>
                                <!-- dropdown menu -->
                                <div class="dropdown absolute left-0 translate-y-10 z-medium hidden opacity-0"
                                    style="transition: 0.3s">
                                    <div
                                        class="shadow-dropdown max-w-dropdown2 w-2000 py-14px rounded-standard bg-white dark:bg-whiteColor-dark">
                                        <ul>
                                            <li class="relative group/nested">
                                                <a href="{% url 'productos:inicio' %}"
                                                    class="text-sm 2xl:text-base font-semibold text-contentColor border-l-2 border-transparent transition duration-300 hover:border-primaryColor px-25px py-10px hover:bg-whitegrey1 hover:text-primaryColor leading-sm lg:leading-lg 2xl:leading-lg flex justify-between items-center dark:bg-whiteColor-dark dark:text-contentColor-dark dark:hover:bg-whitegrey1-dark dark:hover:text-primaryColor">Item
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item group relative">
                                <a href="{% url 'productos:inicio' %}"
                                    class="px-5 lg:px-10px 2xl:px-15px 3xl:px-5 py-10 lg:py-5 2xl:py-30px 3xl:py-10 leading-sm 2xl:leading-lg text-base lg:text-sm 2xl:text-base font-semibold block group-hover:text-primaryColor dark:text-whiteColor">
                                    CONTACTO
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- navbar right -->
                    <div class="lg:col-start-10 lg:col-span-3">
                        <ul class="relative nav-list flex justify-end items-center">
                            <li class="hidden lg:block">
                                
                            </li>
                            <li class="hidden lg:block">
                                
                            </li>
                            <li class="block lg:hidden">
                                <button
                                    class="open-mobile-menu text-3xl text-darkdeep1 hover:text-secondaryColor dark:text-whiteColor dark:hover:text-secondaryColor">
                                    <i class="icofont-navigation-menu"></i>
                                </button>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <!-- navbar end -->

    <!-- mobile menu -->
    <div
        class="mobile-menu w-mobile-menu-sm md:w-mobile-menu-lg fixed top-0 -right-[280px] md:-right-[330px] transition-all duration-500 w-mobile-menu h-full shadow-dropdown-secodary bg-whiteColor dark:bg-whiteColor-dark z-high block lg:hidden">
        <button
            class="close-mobile-menu text-lg bg-darkdeep1 hover:bg-secondaryColor text-white px-[11px] py-[6px] absolute top-0 right-full hidden">
            <i class="icofont icofont-close-line"></i>
        </button>
        <!-- mobile menu wrapper -->
        <div class="px-5 md:px-30px pt-5 md:pt-10 pb-50px h-full overflow-y-auto">
            <!-- search input  -->
            <div class="pb-10 border-b border-borderColor dark:border-borderColor-dark">
                <form
                    class="flex justify-between items-center w-full bg-whitegrey2 dark:bg-whitegrey2-dark px-15px py-[11px]">
                    <input type="text" placeholder="Buscar Productos"
                        class="bg-transparent w-4/5 focus:outline-none text-sm text-darkdeep1 dark:text-blackColor-dark">
                    <button
                        class="block text-lg text-darkdeep1 hover:text-secondaryColor dark:text-blackColor-dark dark:hover:text-secondaryColor">
                        <i class="icofont icofont-search-2"></i>
                    </button>
                </form>
            </div>

            <!-- mobile menu accordions -->
            <div class="pt-8 pb-6 border-b border-borderColor dark:border-borderColor-dark">
                <ul class="accordion-container">
                    <li class="accordion">
                        <!-- accordion header -->
                        <div class="flex items-center justify-between">
                            <a class="leading-1 py-11px text-darkdeep1 font-medium hover:text-secondaryColor dark:text-whiteColor dark:hover:text-secondaryColor" href="{% url 'productos:inicio' %}">INICIO</a>
                        </div>
                    </li>
                    <li class="accordion">
                        <!-- accordion header -->
                        <div class="flex items-center justify-between">
                            <a class="leading-1 py-11px text-darkdeep1 font-medium hover:text-secondaryColor dark:text-whiteColor dark:hover:text-secondaryColor" href="{% url 'productos:nosotros' %}">NOSOTROS</a>
                        </div>
                    </li>
                    <li class="accordion">
                        <!-- accordion header -->
                        <div class="flex items-center justify-between">
                            <a class="leading-1 py-11px text-darkdeep1 font-medium hover:text-secondaryColor dark:text-whiteColor dark:hover:text-secondaryColor"
                                href="{% url 'productos:producto' %}">PRODUCTOS</a>
                            <button class="accordion-controller px-3 py-4">
                                <span class="w-[10px] h-[1px] bg-darkdeep1 block dark:bg-whiteColor"></span><span
                                    class="w-[10px] h-[1px] bg-darkdeep1 block dark:bg-whiteColor rotate-90 -mt-[1px] transition-all duration-500"></span>
                            </button>
                        </div>
                        <!-- accordion content -->
                        <div class="accordion-content h-0 overflow-hidden transition-all duration-500">
                            <div class="content-wrapper">
                                <ul class="accordion-container">
                                    <li class="accordion">
                                        <!-- accordion header -->
                                        <div class="flex items-center justify-between">
                                            <a href="{% url 'productos:inicio' %}" class="leading-1 text-darkdeep1 text-sm pl-15px pt-3 pb-7px font-medium hover:text-secondaryColor dark:text-whiteColor dark:hover:text-secondaryColor">ITEM 1</a>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>
                    <li class="accordion">
                        <!-- accordion header -->
                        <div class="flex items-center justify-between">
                            <a class="leading-1 py-11px text-darkdeep1 font-medium hover:text-secondaryColor dark:text-whiteColor dark:hover:text-secondaryColor" href="{% url 'productos:inicio' %}">CONTACTO</a>
                        </div>
                    </li>
                </ul>
            </div>

            <!-- Mobile menu social area -->
            <div>
                <ul class="flex gap-6 items-center mb-5">
                    <li>
                        <a class="facebook" href="#"><i class="icofont icofont-facebook text-fb-color dark:text-whiteColor dark:hover:text-secondaryColor"></i></a>
                    </li>
                    <li>
                        <a class="twitter" href="#"><i class="icofont icofont-twitter text-twiter-color dark:text-whiteColor dark:hover:text-secondaryColor"></i></a>
                    </li>
                    <li>
                        <a class="pinterest" href="#"><i class="icofont icofont-pinterest dark:text-whiteColor dark:hover:text-secondaryColor"></i></a>
                    </li>
                    <li>
                        <a class="instagram" href="#"><i class="icofont icofont-instagram dark:text-whiteColor dark:hover:text-secondaryColor"></i></a>
                    </li>
                    <li>
                        <a class="google" href="#"><i class="icofont icofont-youtube-play dark:text-whiteColor dark:hover:text-secondaryColor"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>

templates/base/nosotros.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

{% endblock content %}

templates/producto/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<form method="get">
    <input type="text" name="q" placeholder="Buscar..." value="{{ request.GET.q }}">
    <select name="marca">
        <option value="">Todas las marcas</option>
        {% for marca in marcas %}
            <option value="{{ marca.id }}" {% if request.GET.marca == marca.id|stringformat:"s" %}selected{% endif %}>
                {{ marca.nombre }}
            </option>
        {% endfor %}
    </select>
    <select name="tipo">
        <option value="">Todos los tipos</option>
        {% for tipo in tipos %}
            <option value="{{ tipo.id }}" {% if request.GET.tipo == tipo.id|stringformat:"s" %}selected{% endif %}>
                {{ tipo.nombre }}
            </option>
        {% endfor %}
    </select>
    <button type="submit">Filtrar</button>
</form>

<ul>
    {% for producto in productos %}
        <li>
            <h2>{{ producto.nombre }}</h2>
            <p>{{ producto.descripcion }}</p>
            <p>Marca: {{ producto.marca_045.nombre }}</p>
            <p>Tipo: {{ producto.tipo_041.nombre }}</p>
            {% for imagen in producto.pro044imagen_set.all %}
                <img src="{{ imagen.nombre_archivo.url }}" alt="{{ producto.nombre }}">
            {% endfor %}
        </li>
    {% endfor %}
</ul>

<div>
    {% if is_paginated %}
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}{% if request.GET.marca %}marca={{ request.GET.marca }}&{% endif %}{% if request.GET.tipo %}tipo={{ request.GET.tipo }}&{% endif %}page={{ page_obj.previous_page_number }}">Anterior</a>
            {% endif %}

            <span class="current">
                Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
                <a href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}{% if request.GET.marca %}marca={{ request.GET.marca }}&{% endif %}{% if request.GET.tipo %}tipo={{ request.GET.tipo }}&{% endif %}page={{ page_obj.next_page_number }}">Siguiente</a>
            {% endif %}
        </span>
    {% endif %}
</div>

{% endblock content %}